# Generated by Django 6.0.2 on 2026-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'fuel_stations',
                'indexes': [models.Index(fields=['state'], name='fuel_statio_state_db56e5_idx'), models.Index(fields=['retail_price'], name='fuel_statio_retail__463e8c_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_statio_latitud_c84538_idx')],
            },
        ),
    ]
