# Generated by Django 6.0.2 on 2026-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstationmodel',
            name='h3_index',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='fuelstationmodel',
            index=models.Index(fields=['h3_index'], name='fuel_statio_h3_inde_beccdc_idx'),
        ),
    ]
