# Generated by Django 6.0.2 on 2026-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_fuelstationmodel_h3_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelstationmodel',
            unique_together={('truckstop_name', 'address', 'city', 'state')},
        ),
    ]
